import turtle;
turtle.shape("turtle");
turtle.forward(25);
turtle.left(90);
turtle.forward(25);
turtle.left(90);
turtle.forward(25);
turtle.left(90);
turtle.forward(25);
turtle.left(90);
turtle.exitonclick();